name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # yoki master bo‘lsa o‘shani yozing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/cloude_project
            git pull origin main
            pm2 restart all || pm2 start backend/index.js --name backend
          EOF
